name: Task
description: Create a development task
title: "[TASK]: "
body:
  - type: markdown
    attributes:
      value: |
        Create a task for development work.
  
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task clearly
    validations:
      required: true
  
  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks
      description: Break down the task into smaller steps
      placeholder: |
        - [ ] Subtask 1
        - [ ] Subtask 2
        - [ ] Subtask 3
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of task is this?
      options:
        - Frontend
        - Backend
        - Database
        - DevOps
        - Documentation
        - Testing
        - Design
    validations:
      required: true
  
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical details, dependencies, or constraints
  
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: When is this task considered complete?
      placeholder: |
        - [ ] Code written and tested
        - [ ] Code reviewed
        - [ ] Tests pass locally
